name: story_recom
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py38h06a4308_2
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - faiss-gpu=1.7.2=py3.8_h28a55e0_0_cuda11.3
  - intel-openmp=2021.4.0=h06a4308_3561
  - libedit=3.1.20210910=h7f8727e_0
  - libfaiss=1.7.2=hfc2d529_0_cuda11.3
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - numpy=1.21.2=py38h20f2e39_0
  - numpy-base=1.21.2=py38h79a1101_0
  - openssl=1.1.1m=h7f8727e_0
  - pip=21.2.2=py38h06a4308_0
  - python=3.8.0=h0371630_2
  - readline=7.0=h7b6447c_5
  - setuptools=58.0.4=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - attrs==21.4.0
    - beautifulsoup4==4.10.0
    - blis==0.7.5
    - catalogue==2.0.6
    - charset-normalizer==2.0.9
    - click==8.0.3
    - cycler==0.11.0
    - cymem==2.0.6
    - et-xmlfile==1.1.0
    - filelock==3.4.0
    - fonttools==4.28.4
    - future==0.18.2
    - gdown==4.2.0
    - huggingface-hub==0.0.19
    - idna==3.3
    - jinja2==3.0.3
    - joblib==1.1.0
    - jsonlines==3.0.0
    - kiwisolver==1.3.2
    - langcodes==3.3.0
    - markupsafe==2.1.0
    - matplotlib==3.5.0
    - murmurhash==1.0.6
    - nltk==3.6.5
    - openpyxl==3.0.9
    - packaging==21.3
    - pandas==1.3.4
    - pathy==0.6.1
    - pillow==8.4.0
    - preshed==3.0.6
    - pydantic==1.8.2
    - pyparsing==3.0.6
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - regex==2021.11.10
    - requests==2.26.0
    - sacremoses==0.0.46
    - scikit-learn==0.24.2
    - scipy==1.7.3
    - sentencepiece==0.1.96
    - setuptools-scm==6.3.2
    - smart-open==5.2.1
    - soupsieve==2.3.1
    - spacy==3.2.2
    - spacy-legacy==3.0.9
    - spacy-loggers==1.0.1
    - srsly==2.4.2
    - thinc==8.0.13
    - threadpoolctl==3.0.0
    - tokenizers==0.8.1rc1
    - tomli==2.0.0
    - torch==1.6.0
    - torchtext==0.11.0
    - tqdm==4.62.3
    - transformers==3.0.2
    - typer==0.4.0
    - typing-extensions==4.0.1
    - urllib3==1.26.7
    - wasabi==0.9.0
prefix: /home/CE/nbafna/anaconda3/envs/story_recom
